/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    public void constructorTest() {
        App testApp = new App();
        assertNotNull(testApp);
    }
    
    
    // public static void main(String[] args) {
    //     App testApp = new App();
    //     testApp.gameManager.setUp();
    //     testApp.draw();
    // }
}
